### ISSUE TITLE
Obtain authorization for 500px

### ISSUE THREAD

**Issue by IgorMedved** [IgorMedved/DevChallenge#6]
@anurlybayev

**Comment by anurlybayev** [comment]
If you're hitting `/photos` end point you do not need to do full OAuth. According to [documentation](https://github.com/500px/api-documentation/blob/master/endpoints/photo/GET_photos.md#requires-authentication), you could use just **consumer key** as parameter.

**Comment by IgorMedved** [comment]
Yes, I realized that, thanks!
